(ert-deftest zotero-cache--mergable-plist-p ()
  "Test"
  (should (zotero-cache--mergable-plist-p '(:a 1 :b 2) '(:c 3)))
  (should (zotero-cache--mergable-plist-p '(:a 1 :b 2) '(:a 1 :c 3)))
  (should (zotero-cache--mergable-plist-p '(:a :json-false :c 3) '(:a 1 :b 2)))
  (should (zotero-cache--mergable-plist-p '(:a :json-empty :c 3) '(:a 1 :b 2)))
  (should (zotero-cache--mergable-plist-p '(:a 1 :b 2) '(:a :json-false :c 3)))
  (should (zotero-cache--mergable-plist-p '(:a 1 :b 2) '(:a :json-empty :c 3)))
  (should (not (zotero-cache--mergable-plist-p '(:a 1 :b 2) '(:a 2 :c 3)))))

(ert-deftest zotero-cache--merge-plist ()
  (should (equal (zotero-cache--merge-plist '(:a 1 :b 2) '(:c 3)) '(:a 1 :b 2 :c 3)))
  (should (equal (zotero-cache--merge-plist '(:a 1 :b 2) '(:a 1 :c 3)) '(:a 1 :b 2 :c 3)))
  (should (equal (zotero-cache--merge-plist '(:a :json-false :b 2) '(:a 1 :c 3)) '(:a 1 :b 2 :c 3)))
  (should (equal (zotero-cache--merge-plist '(:a :json-empty :b 2) '(:a 1 :c 3)) '(:a 1 :b 2 :c 3)))
  (should (equal (zotero-cache--merge-plist '(:a 1 :b 2) '(:a :json-false :c 3)) '(:a 1 :b 2 :c 3)))
  (should (equal (zotero-cache--merge-plist '(:a 1 :b 2) '(:a :json-empty :c 3)) '(:a 1 :b 2 :c 3))))

(ert-deftest zotero-cache--read-access-p ()
  (should (zotero-cache--read-access-p '(:library t)))
  (should-not (zotero-cache--read-access-p '(:library :json-false)))
  (should-not (zotero-cache--read-access-p '(:library nil))))

(ert-deftest zotero-cache--write-access-p ()
  (should (zotero-cache--write-access-p '(:library t :write t)))
  (should-not (zotero-cache--write-access-p '(:library t :write :json-false)))
  (should-not (zotero-cache--write-access-p '(:library t :write nil))))

(ert-deftest zotero-cache--read-only-p ()
  (should (zotero-cache--read-only-p '(:library t :write :json-false)))
  (should (zotero-cache--read-only-p '(:library t :write nil)))
  (should-not (zotero-cache--read-only-p '(:library t :write t)))
  (should-not (zotero-cache--read-only-p '(:library :json-false :write :json-false)))
  (should-not (zotero-cache--read-only-p '(:library nil :write nil))))
